/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HostGUI.java
 *
 * Created on Nov 27, 2016, 7:37:59 PM
 */

package org.sunspotworld;

//import com.sun.spot.peripheral.ota.IOTACommandServer;
//import com.sun.spot.peripheral.ota.OTACommandServer;

import java.io.*;
import java.awt.*;
import java.awt.event.*;
import java.awt.print.*;
import javax.swing.*;
import java.util.*;
import java.text.*;


/**
 *
 * @author userrsus
 */
public class HostGUI extends JFrame {

    private static RadioTools listener = null;

    private static Vector windows = new Vector();
    private static int numWindows = 0;


    /**
     * Creates a new TelemetryFrame window.
     */
    public HostGUI() {
        init();
    }

    /**
     * Initialize the new HostGUI
     */
    private void init() {
        Random rand = new Random();

        if (listener == null) {
            listener = new RadioTools();         // only need one
            listener.start();
        }
        //listener.setGUI(this);
        initComponents();
        //Areas no visibles
        node1.setVisible(false);
        node2.setVisible(false);
        node3.setVisible(false);
        node4.setVisible(false);
        jButton5.setVisible(false);

        jTextArea1.setEditable(false);
        jTextArea4.setEditable(false);

        //Iniciamos valores limites
        jTable1.setValueAt( rand.nextFloat(), 0, 1);
        jTable1.setValueAt( rand.nextFloat(), 1, 1);
        jTable1.setValueAt( rand.nextFloat(), 2, 1);
        jTable1.setValueAt( rand.nextFloat(), 3, 1);
        jTable1.setValueAt( rand.nextFloat(), 4, 1);
        jTable1.setValueAt( rand.nextFloat(), 5, 1);
    }

    /**
     * Display the current connection status to a remote SPOT.
     * Called by the AccelerometerListener whenever the radio connection status changes.
     *
     * @param conn true if now connected to a remote SPOT
     * @param msg the String message to display, includes the
     */
//    public void setConnectionStatus(boolean conn, String msg) {
//
//        conn = true;
//        connStatusLabel.setText(msg);
//        //jTextArea4.append( msg + ".\n");
//        node1.setEnabled(conn);
//        node2.setEnabled(conn);
//        node3.setEnabled(conn);
//        node4.setEnabled(conn);
//        jButton5.setEnabled(conn);
//        changeLimits.setEnabled(conn);
//    }


    /**
     *
     *
     * @param conn true if now connected to a remote SPOT
     */
    public void newArea (int numArea, String addrAgg ) {

        if ( numArea == 1 )
            node1.setVisible(true);
        else if ( numArea == 2 )
            node2.setVisible(true);
        else if ( numArea == 3 )
            node3.setVisible(true);
        else if ( numArea == 4 )
            node4.setVisible(true);

        this.log( "New Area Added. New addres:  " + addrAgg );

    }

    /**
     *
     *
     * @param conn true if now connected to a remote SPOT
     */
    public void log (String msg) {
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm");
        Date date = new Date();
        //System.out.println(dateFormat.format(date)); //2016/11/16 12:08:43

        jTextArea4.append( dateFormat.format(date) + ":   " + msg + ".\n");
        jTextArea4.setCaretPosition(jTextArea4.getDocument().getLength());
    }

    /**
     *
     *
     * @param conn true if now connected to a remote SPOT
     */
    public void logAlarm (String msg) {
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm");
        Date date = new Date();
        //System.out.println(dateFormat.format(date)); //2016/11/16 12:08:43

        jTextArea1.append( dateFormat.format(date) + ":   " + msg + ".\n");
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }

    /**
     *
     *
     * @param conn true if now connected to a remote SPOT
     */
    public void displayInfo (int area, String addr, String temp, String ph, String ec ) {
        jTable3.setValueAt( String.valueOf(area), 0, 1);
        jTable3.setValueAt( addr, 1, 1);
        jTable3.setValueAt( "XXX", 2, 1);
        jTable3.setValueAt( temp, 3, 1);
        jTable3.setValueAt( ph, 4, 1);
        jTable3.setValueAt( ec, 5, 1);
    }

    /**
     * Cleanly exit.
     */
    private void doQuit() {
        listener.doQuit();
        System.exit(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new java.awt.Panel();
        node2 = new javax.swing.JButton();
        node4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        node3 = new javax.swing.JButton();
        node1 = new javax.swing.JButton();
        changeLimits = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        connStatusLabel1 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        connStatusLabel2 = new javax.swing.JLabel();
        list1 = new java.awt.List();
        jLabel7 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        panel3 = new java.awt.Panel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PRECISSION AGRICULTURE");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });

        node2.setText("Area2");
        node2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2ActionPerformed(evt);
            }
        });

        node4.setText("Area4");
        node4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area4ActionPerformed(evt);
            }
        });

        jButton5.setText("Agg1");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        node3.setText("Area3");
        node3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area3ActionPerformed(evt);
            }
        });

        node1.setText("Area1");
        node1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1ActionPerformed(evt);
            }
        });

        changeLimits.setText("ChangeLimits");
        changeLimits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeLimitsActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Min Temp", null},
                {"Max Temp", null},
                {"Min pH", null},
                {"Max pH", null},
                {"Min EC", null},
                {"Max EC", null}
            },
            new String [] {
                "Params", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable1);

        connStatusLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        connStatusLabel1.setText("Info");
        connStatusLabel1.setFocusTraversalPolicyProvider(true);
        connStatusLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        connStatusLabel1.setMaximumSize(new java.awt.Dimension(320, 16));
        connStatusLabel1.setMinimumSize(new java.awt.Dimension(145, 16));
        connStatusLabel1.setPreferredSize(new java.awt.Dimension(245, 16));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"N? Area", null},
                {"ID", null},
                {"PORT", null},
                {"TEMPERATURE (C)", null},
                {"pH", null},
                {"EC", null}
            },
            new String [] {
                "Params", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable3);

        connStatusLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        connStatusLabel2.setText("VALUE LIMITS");
        connStatusLabel2.setFocusTraversalPolicyProvider(true);
        connStatusLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        connStatusLabel2.setMaximumSize(new java.awt.Dimension(320, 16));
        connStatusLabel2.setMinimumSize(new java.awt.Dimension(145, 16));
        connStatusLabel2.setPreferredSize(new java.awt.Dimension(245, 16));

        org.jdesktop.layout.GroupLayout panel2Layout = new org.jdesktop.layout.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(panel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(panel2Layout.createSequentialGroup()
                        .add(panel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(node1)
                            .add(node3))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(panel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(node2)
                            .add(node4)))
                    .add(panel2Layout.createSequentialGroup()
                        .add(35, 35, 35)
                        .add(jButton5))
                    .add(changeLimits))
                .add(18, 18, 18)
                .add(panel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, panel2Layout.createSequentialGroup()
                        .add(jScrollPane6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 315, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jScrollPane5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 164, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(35, 35, 35))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, panel2Layout.createSequentialGroup()
                        .add(connStatusLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 261, Short.MAX_VALUE)
                        .add(connStatusLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 119, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(65, 65, 65))))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(panel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(panel2Layout.createSequentialGroup()
                        .add(panel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(node1)
                            .add(node2))
                        .add(20, 20, 20)
                        .add(jButton5)
                        .add(18, 18, 18)
                        .add(panel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(node3)
                            .add(node4))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(changeLimits))
                    .add(panel2Layout.createSequentialGroup()
                        .add(panel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(connStatusLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(connStatusLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(panel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jScrollPane6, 0, 0, Short.MAX_VALUE)
                            .add(jScrollPane5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel7.setText("Precision Agriculture");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel8.setText("ALARMS");

        org.jdesktop.layout.GroupLayout panel1Layout = new org.jdesktop.layout.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(panel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 652, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 139, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel8)
                .add(10, 10, 10)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        jLabel9.setText("LOG");

        org.jdesktop.layout.GroupLayout panel3Layout = new org.jdesktop.layout.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(panel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 647, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 139, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel9)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, panel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, panel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 139, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, panel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jLabel7)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void area2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2ActionPerformed
        // TODO add your handling code here:
        //jTextArea4.append("get temperature of Node 2.\n");
        listener.doGetMeasures(2);
}//GEN-LAST:event_area2ActionPerformed

    private void area4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area4ActionPerformed
        // TODO add your handling code here:
        //jTextArea4.append("get temperature of Node 4.\n");
        listener.doGetMeasures(4);
}//GEN-LAST:event_area4ActionPerformed

    private void area3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area3ActionPerformed
        // TODO add your handling code here:
        //jTextArea4.append("get temperature of Node 3.\n");
        listener.doGetMeasures(3);
}//GEN-LAST:event_area3ActionPerformed

    private void area1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1ActionPerformed
        // TODO add your handling code here:
        //this.log( "get temperature of Node 1." );
        //jTextArea4.append("get temperature of Node 1.\n");
        listener.doGetMeasures(1);
}//GEN-LAST:event_area1ActionPerformed

    private void changeLimitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeLimitsActionPerformed
        // TODO add your handling code here:
        //jTextArea4.append("Set new limits value.\n");

        this.log( "Set new limits value." );

        String dato1 = String.valueOf(jTable1.getValueAt( 0, 1));
        String dato2 = String.valueOf(jTable1.getValueAt( 1, 1));
        String dato3 = String.valueOf(jTable1.getValueAt( 2, 1));
        String dato4 = String.valueOf(jTable1.getValueAt( 3, 1));
        String dato5 = String.valueOf(jTable1.getValueAt( 4, 1));
        String dato6 = String.valueOf(jTable1.getValueAt( 5, 1));

        float tempMin   = Float.parseFloat(dato1);
        float tempMax   = Float.parseFloat(dato2);
        float phMin     = Float.parseFloat(dato3);
        float phMax     = Float.parseFloat(dato4);
        float ecMin     = Float.parseFloat(dato5);
        float ecMax     = Float.parseFloat(dato6);

        //leer valores y enviar
        listener.doSetLimits( tempMin, tempMax, phMin, phMax,  ecMin, ecMax );
}//GEN-LAST:event_changeLimitsActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
//        jTable3.setValueAt( "7F00.0101.0000.1001", 0, 1);
//        jTable3.setValueAt( "100", 1, 1);
//        jTable3.setValueAt( "15.24", 2, 1);
//        jTable3.setValueAt( "5.5", 3, 1);
//        jTable3.setValueAt( "11.87", 4, 1);
        Random rand = new Random();
        //cambiamos valores limites
        jTable1.setValueAt( rand.nextFloat(), 0, 1);
        jTable1.setValueAt( rand.nextFloat(), 1, 1);
        jTable1.setValueAt( rand.nextFloat(), 2, 1);
        jTable1.setValueAt( rand.nextFloat(), 3, 1);
        jTable1.setValueAt( rand.nextFloat(), 4, 1);
        jTable1.setValueAt( rand.nextFloat(), 5, 1);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listener.setGUI(this);
    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        windows.remove(this);
        if (--numWindows <= 0) {
            doQuit();
        }
    }//GEN-LAST:event_formWindowClosed

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        //listener.setGUI(null);
    }//GEN-LAST:event_formWindowDeactivated



    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HostGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeLimits;
    private javax.swing.JLabel connStatusLabel1;
    private javax.swing.JLabel connStatusLabel2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea4;
    private java.awt.List list1;
    private javax.swing.JButton node1;
    private javax.swing.JButton node2;
    private javax.swing.JButton node3;
    private javax.swing.JButton node4;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    // End of variables declaration//GEN-END:variables

}
